config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'question' => 'questions#show'
  get 'questions' => 'questions#index'
end

app/models/question.rb
class Question < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def questions_json(questions)
    result = []
    questions.each do |question|
      hash = question.as_json
      result << hash
    end
    result.to_json
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @questions = questions_json(Question.all)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phone Interview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<h1>Interview Questions</h1>

<ol>
  <% @questions.each do |question| %>
  <li><%= question.content %></li>
  <% end %>
</ol>

<%= link_to 'Back', root_path, class: 'button' %>

app/views/questions/show.html.erb
<div data-container="question">
</div>

<a href="#" class="button" data-behavior="get">Ask me another</a>  <%= link_to 'Stop interview', root_path, class: 'button' %>

<script>
  $(document).ready(QuestionGenerator.initialize(<%= raw @questions %>));
</script>

app/views/welcome/index.html.erb
<h1>Phone Interview</h1>
<p>An app to help job applicants to practice their phone interviewing responses.
</p>

<%= link_to 'Start Interviewing', question_path, :class => 'button' %>
<%= link_to 'View All Interview Questions', questions_path, :class => 'button' %>